name: .NET Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Check out Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run cake
        shell : bash
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet tool install Cake.Tool --version 1.1.0
          dotnet tool restore
          dotnet cake --target=Report --verbosity=verbose
      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: code_coverage/results.info 